'Getting Started':
  'quickstart-guide': 'Quickstart Guide'
  'write-proper-video-elements': 'Write <video> elements'
  'encode-videos-for-the-web': 'Video encoding'
  'create-poster-frame': 'Create poster frame'
'How To':
  'lightbox': 'Floating lightbox'
  'hd-switching': 'HD switching'
  'playlists': 'Playlists'
  'custom-play-button': 'Custom play button'
  'autoplay': 'Autoplay a video'
  'loop': 'Loop a video'
  'responsive-layout': 'Responsive layout'
  'back-to-initial-state-on-end': 'Back to initial state on end'
  'embeds': 'Embeds'
  'optimize-for-stats': 'Optimize <video> for stats'
  'ssl': 'SSL Serving'
  'google-analytics-integration': 'Google Analytics integration'
'Javascript API':
  'javascript-api/usage': 'Usage'
  'javascript-api/methods': 'Methods'
  'javascript-api/listeners': 'Listeners'
'Integration Tools':
  'video-code-generator': 'Video code generator'
  'wordpress': 'WordPress plugin'
'Service':
  'real-time-stats': 'Real-Time Statistics'
  'peak-insurance': 'Peak insurance'
  'site-settings': 'Site settings'
'Other':
  'faq': 'FAQ'
  'troubleshooting': 'Troubleshooting'
  'supported-browsers-and-platforms': 'Supported platforms'
  'releases': 'Release Notes'
