stable:
  'Getting Started':
    'quickstart-guide': 'Quickstart Guide'
    'write-proper-video-elements': 'Write <video> elements'
    'encode-videos-for-the-web': 'Video encoding'
    'create-poster-frame': 'Create poster frame'
  'How To':
    'lightbox': 'Floating lightbox'
    'hd-switching': 'HD switching'
    'playlists': 'Playlists'
    'custom-start-view': 'Custom start view'
    'autoplay': 'Autoplay a video'
    'loop': 'Loop a video'
    'responsive-layout': 'Responsive layout'
    'back-to-initial-state-on-end': 'Back to initial state on end'
    'embeds': 'Embeds'
    'google-analytics-integration': 'Google Analytics integration'
  'Javascript API':
    'javascript-api/usage': 'Usage'
    'javascript-api/methods': 'Methods'
    'javascript-api/listeners': 'Listeners'
  'Integration Tools':
    'video-publishing-assistant': 'Video publishing assistant'
    'wordpress': 'WordPress plugin'
  'Service':
    'addons/stats': 'Real-Time Statistics'
    'site-settings': 'Site settings'
  'Other':
    'player-faq': 'Player FAQ'
    'service-faq': 'Service FAQ'
    'troubleshooting': 'Troubleshooting'
    'supported-platforms': 'Supported platforms'
    'releases': 'Release Notes'
beta:
  'Getting Started':
    'quickstart-guide': 'Quickstart Guide'
    'troubleshooting': 'Troubleshooting'
    'player-faq': 'Player FAQ'
    'service-faq': 'Service FAQ'
  'Video Hosting':
    'youtube': 'YouTube'
    'vimeo-pro': 'Vimeo Pro'
  'Built-in Features':
    'lightbox': 'Lightbox'
    'hd-switching': 'HD switching'
    'responsive-layout': 'Responsive layout'
    'keyboard': 'Keyboard control'
  'Add-Ons':
    'addons/stats': 'Real-Time Statistics'
    'addons/on-video-logo': 'On-Video Logo'
    'addons/sharing': 'Social Sharing'
  'Integration':
    'custom-start-view': 'Custom start view'
    'wordpress': 'WordPress plugin'
    'playlists': 'Playlists'
    'video-publishing-assistant': 'Video publishing assistant'
    'google-analytics-integration': 'Google Analytics integration'
    'embeds': 'Embeds'
  'Settings':
    'settings/usage': 'Usage'
    'settings/player-settings': 'Player settings'
    'settings/lightbox-settings': 'Lightbox settings'
  'Javascript API':
    'javascript-api/usage': 'Usage'
    'javascript-api/application': 'Application'
    'javascript-api/player': 'Player'
    'javascript-api/lightbox': 'Lightbox'
  'Other':
    'write-proper-video-elements': 'Write <video> elements'
    'encode-videos-for-the-web': 'Video encoding'
    'create-poster-frame': 'Create poster frame'
    'supported-platforms': 'Supported platforms'
    'site-settings': 'Site settings'
    'releases': 'Release Notes'
