stable:
  'Getting Started':
    'quickstart-guide': 'Quickstart Guide'
    'write-proper-video-elements': 'Write <video> elements'
    'encode-videos-for-the-web': 'Video encoding'
    'create-poster-frame': 'Create poster frame'
  'How To':
    'lightbox': 'Floating lightbox'
    'hd-switching': 'HD switching'
    'playlists': 'Playlists'
    'custom-start-view': 'Custom start view'
    'autoplay': 'Autoplay a video'
    'loop': 'Loop a video'
    'responsive-layout': 'Responsive layout'
    'back-to-initial-state-on-end': 'Back to initial state on end'
    'embeds': 'Embeds'
    'optimize-for-stats': 'Optimize <video> for stats'
    'google-analytics-integration': 'Google Analytics integration'
  'Javascript API':
    'javascript-api/usage': 'Usage'
    'javascript-api/methods': 'Methods'
    'javascript-api/listeners': 'Listeners'
  'Integration Tools':
    'video-publishing-assistant': 'Video publishing assistant'
    'wordpress': 'WordPress plugin'
  'Service':
    'real-time-stats': 'Real-Time Statistics'
    'peak-insurance': 'Peak insurance'
    'site-settings': 'Site settings'
  'Other':
    'player-faq': 'Player FAQ'
    'service-faq': 'Service FAQ'
    'troubleshooting': 'Troubleshooting'
    'supported-platforms': 'Supported platforms'
    'releases': 'Release Notes'
beta:
  'Getting Started':
    'quickstart-guide': 'Quickstart Guide'
    'whats-new': "What's new in Beta?"
    'write-proper-video-elements': 'Write <video> elements'
    'video-publishing-assistant': 'Video publishing assistant'
    'encode-videos-for-the-web': 'Video encoding'
    'create-poster-frame': 'Create poster frame'
    'Settings':
      'settings/usage': 'Usage'
      'settings/player-settings': 'Player settings'
      'settings/lightbox-settings': 'Lightbox settings'
    'site-settings': 'Site settings'
    'troubleshooting': 'Troubleshooting'
    'player-faq': 'Player FAQ'
    'service-faq': 'Service FAQ'
  'Add-ons':
    #'addons/on-video-logo': 'On-Video Logo'
    'Real-Time Statistics':
      'addons/real-time-stats/overview': 'Overview'
      'addons/real-time-stats/optimize-for-stats': 'Optimize <video> for stats'
  'Hosting Integration':
    'youtube': 'YouTube'
    'vimeo-pro': 'Vimeo Pro'
  'CMS Integration':
    'wordpress': 'WordPress plugin'
  'Integration':
    'lightbox': 'Lightbox'
    'playlists': 'Playlists'
    'responsive-layout': 'Responsive layout'
    'hd-switching': 'HD switching'
    'custom-start-view': 'Custom start view'
    'google-analytics-integration': 'Google Analytics integration'
    'embeds': 'Embeds'
    # 'autoplay': 'Autoplay a video'
    # 'custom-behavior-on-end': 'Custom behavior on end'
  'Javascript API':
    'javascript-api/usage': 'Usage'
    'javascript-api/application': 'Application'
    'javascript-api/player': 'Player'
    'javascript-api/lightbox': 'Lightbox'
  'Other':
    'supported-platforms': 'Supported platforms'
    'keyboard': 'Keyboard control'
    'releases': 'Release Notes'
