stable:
  'Getting Started':
    'quickstart-guide': 'Quickstart Guide'
    'write-proper-video-elements': 'Write <video> elements'
    'encode-videos-for-the-web': 'Video encoding'
    'create-poster-frame': 'Create poster frame'
  'How To':
    'lightbox': 'Floating lightbox'
    'hd-switching': 'HD switching'
    'playlists': 'Playlists'
    'custom-start-view': 'Custom start view'
    'autoplay': 'Autoplay a video'
    'loop': 'Loop a video'
    'responsive-layout': 'Responsive layout'
    'back-to-initial-state-on-end': 'Back to initial state on end'
    'embeds': 'Embeds'
    'optimize-for-stats': 'Optimize <video> for stats'
    'google-analytics-integration': 'Google Analytics integration'
  'Javascript API':
    'javascript-api/usage': 'Usage'
    'javascript-api/methods': 'Methods'
    'javascript-api/listeners': 'Listeners'
  'Integration Tools':
    'video-code-generator': 'Video code generator'
    'wordpress': 'WordPress plugin'
  'Service':
    'real-time-stats': 'Real-Time Statistics'
    'peak-insurance': 'Peak insurance'
    'site-settings': 'Site settings'
  'Other':
    'player-faq': 'Player FAQ'
    'service-faq': 'Service FAQ'
    'troubleshooting': 'Troubleshooting'
    'supported-browsers-and-platforms': 'Supported platforms'
    'releases': 'Release Notes'
beta:
  'Getting Started':
    'whats-new': "What's new?"
    'quickstart-guide': 'Quickstart Guide'
    'write-proper-video-elements': 'Write <video> elements'
    'video-code-generator': 'Video code generator'
    'video-hosting': 'Video hosting'
    'encode-videos-for-the-web': 'Video encoding'
    'create-poster-frame': 'Create poster frame'
    'player-settings': 'Player settings'
    'site-settings': 'Site settings'
    'troubleshooting': 'Troubleshooting'
    'player-faq': 'Player FAQ'
    'service-faq': 'Service FAQ'
  'Add-ons':
    'addons/logo': 'Logo'
    'addons/lightbox': 'Lightbox'
    'Real-Time Statistics':
      'addons/real-time-stats/overview': 'Overview'
      'addons/real-time-stats/optimize-for-stats': 'Optimize <video> for stats'
  'Integration':
    'wordpress': 'WordPress plugin'
    'hd-switching': 'HD switching'
    'playlists': 'Playlists'
    'custom-start-view': 'Custom start view'
    'autoplay': 'Autoplay a video'
    'custom-behavior-on-end': 'Custom behavior on end'
    'responsive-layout': 'Responsive layout'
    'embeds': 'Embeds'
    'google-analytics-integration': 'Google Analytics integration'
  'Javascript API':
    'javascript-api/usage': 'Usage'
    'javascript-api/methods': 'Methods'
    'javascript-api/listeners': 'Listeners'
  'Other':
    'supported-browsers-and-platforms': 'Supported platforms'
    'detailed-supported-browsers-and-platforms': 'Detailed supported platforms'
    'releases': 'Release Notes'
